# Generated by Django 4.2.16 on 2024-11-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='due',
        ),
        migrations.RemoveField(
            model_name='card',
            name='start',
        ),
        migrations.RemoveField(
            model_name='kanban',
            name='image_file',
        ),
    ]
