# Generated by Django 4.2.16 on 2024-11-20 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_remove_card_due_remove_card_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='column',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
